import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HomePage from "@/components/HomePage";
import Header from "@/components/Header";
import About from "@/components/About";
import Services from "@/components/Services";
import Process from "@/components/Process";
import Features from "@/components/Features";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import logo from "../Assets/logo.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Akeshya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <HomePage />
      <About />
      <Services />
      <Process />
      <Features />
      <Contact />
      <Footer />
      <main className={styles.main}>
        <Header />
      </main>
    </>
  );
}
